[sigma_bar]#specal block can not delete
width=1920
height=20
update_grid=0.5
#default font is ProggyClean.ttf that dearpygui default font
#fc-list command can show the fonts been installed
#generally fonts at /usr/share/fonts/opentype
#example:font=/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc
font_size=20
background_color_r=0
background_color_g=0
background_color_b=0
text_color_r=255
text_color_g=255
text_color_b=255

[time]
command=date
