[sigma_bar]
#specal block can not delete
width=1920
height=30
x=0
y=0
#split_sign=
update_grid=0.5
font=/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc
font_size=20
#fc-list command can show the fonts been installed
#generally fonts at /usr/share/fonts/opentype
background_color_r=0
background_color_g=0
background_color_b=0
text_color_r=255
text_color_g=255
text_color_b=255
[time]
#command=date '+%Y-%m-%d %H:%M:%S'
command=date
#label=
[volume]
label=volume:
command=echo -n $(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}'&&echo "(" &&echo $(pactl get-sink-mute @DEFAULT_SINK@) && echo ")" && echo $(pactl get-default-sink))

